ARG base_image
FROM ${base_image} as base

WORKDIR /app

COPY app app/
COPY bootstrap bootstrap/
COPY config config/
COPY database database/
COPY public public/
COPY resources resources/
COPY storage storage/
COPY vendor vendor/
COPY artisan composer.json composer.lock ./

RUN chown -R www-data:www-data storage bootstrap/cache

RUN php artisan octane:install --server=frankenphp -n

ENTRYPOINT ["php", "artisan", "octane:frankenphp", "--host", "0.0.0.0", "--port", "80"]
