sonar.projectKey=laravel-realworld
sonar.projectName=Laravel RealWorld
sonar.sourceEncoding=UTF-8
sonar.sources=app
sonar.tests=tests
sonar.test.inclusions=tests/**/*.php
sonar.php.coverage.reportPaths=coverage.xml
