version: "3"

tasks:
  prepare:
    cmds:
      - touch .env
      - rm .env.testing
  install:
    cmds:
      - composer install
  lint:
    cmds:
      - ./vendor/bin/pint --test
      - ./vendor/bin/phpstan analyse --ansi
  build:
    cmds:
      - php artisan migrate --env=testing
  test:
    cmds:
      - php artisan test --coverage --min=90
