on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: /root/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
  build:
    runs-on: ubuntu-latest
    needs: checkout
    container:
      image: gitea.okami101.io/okami101/php-qa:8.3
    env:
      COMPOSER_ALLOW_SUPERUSER: 1
      DB_CONNECTION: pgsql
      DB_HOST: ${{ vars.POSTGRESQL_HOST }}
      DB_PORT: 5432
      DB_DATABASE: conduit_laravel_test
      DB_USERNAME: test
      DB_PASSWORD: test
    steps:
      - uses: https://gitea.okami101.io/okami101/actions/task@main
      # - uses: sonarsource/sonarqube-scan-action@v2
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      - uses: https://gitea.okami101.io/okami101/actions/docker@main
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
